#!/usr/bin/env python
"""Summary tables for Stage 2a (training-free compression floor)."""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from ccl.metrics import aggregate  # noqa: E402


def _md(headers: list[str], rows: list[list[str]]) -> str:
    return "\n".join(
        ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
        + ["| " + " | ".join(r) + " |" for r in rows]
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results/raw/stage2a_trainfree_drawA.json")
    ap.add_argument("--outdir", default="results/tables")
    args = ap.parse_args()

    data = json.load(open(args.results, encoding="utf-8"))
    rows = data["rows"]
    draw = data["draw"]
    os.makedirs(args.outdir, exist_ok=True)

    with open(os.path.join(args.outdir, f"stage2a_rows_draw{draw}.csv"), "w",
              newline="", encoding="utf-8") as fh:
        fields = ["condition", "ratio", "strategy", "position_mode", "doc_id",
                  "target_tokens", "fact_class", "gold", "prediction", "clean_hit",
                  "semantic_hit", "exact_hit", "distractor_hit", "rank_margin",
                  "answer_logprob", "n_active_positions", "n_doc_tokens"]
        w = csv.DictWriter(fh, fieldnames=fields, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)

    def sel(cond: str, ratio: float | None = None, length: int | None = None):
        return [r for r in rows
                if r["condition"] == cond
                and (ratio is None or r["ratio"] == ratio)
                and (length is None or r["target_tokens"] == length)]

    def line(sub: list[dict]) -> tuple[str, str, str]:
        if not sub:
            return "-", "-", "-"
        a = aggregate(sub)["overall"]
        active = sum(r["n_active_positions"] for r in sub) / len(sub)
        return f"{a['clean_hit']:.3f}", f"{a.get('rank_margin', 0):+.2f}", f"{active:.0f}"

    ratios = sorted({r["ratio"] for r in rows if r["ratio"] > 1})
    reduced = ["KV_STRIDE", "KV_SINK", "KV_STRIDE_COMPACT", "BUDGET"]
    unreduced = ["NATIVE_CACHED", "RANDOM", "SHUFFLE_KV_ORDER", "SHUFFLE_TEXT"]

    md = [
        f"# Stage 2a — training-free compression floor (draw {draw})",
        "",
        f"Model `{data['model_id']}` · {data['n_documents']} documents · "
        f"{data['n_rows']} evaluations · commit `{data['git_commit']}` · "
        f"{data['timestamp_utc']}",
        "",
        "Generated by `scripts/make_tables_s2a.py`. Do not hand-edit.",
        "",
        "Purpose: find the floor a **learned** compressor has to beat, before writing a "
        "training loop. Metric is `clean_hit` (correct and not fooled by the matched "
        "distractor); `margin` is mean `logprob(gold) − logprob(distractor)`.",
        "",
        "## Full-budget references and controls (no reduction)",
        "",
        _md(["condition", "clean_hit", "margin", "active positions"],
            [[c, *line(sel(c))] for c in unreduced]),
        "",
        "## Compression sweep",
        "",
        _md(["condition", *[f"{r:.0f}×" for r in ratios]],
            [[c, *[line(sel(c, r))[0] for r in ratios]] for c in reduced]),
        "",
        "### rank margin (same sweep)",
        "",
        _md(["condition", *[f"{r:.0f}×" for r in ratios]],
            [[c, *[line(sel(c, r))[1] for r in ratios]] for c in reduced]),
        "",
        "### mean active target positions",
        "",
        _md(["condition", *[f"{r:.0f}×" for r in ratios]],
            [[c, *[line(sel(c, r))[2] for r in ratios]] for c in reduced]),
        "",
    ]

    lengths = sorted({r["target_tokens"] for r in rows})
    if len(lengths) > 1:
        md += [
            "## By context length (`clean_hit`)",
            "",
            _md(["condition", "ratio", *[str(x) for x in lengths]],
                [[c, f"{r:.0f}×", *[line(sel(c, r, x))[0] for x in lengths]]
                 for c in reduced for r in ratios]),
            "",
        ]

    path = os.path.join(args.outdir, f"stage2a_report_draw{draw}.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(md) + "\n")
    print("\n".join(md))
    print(f"\nwrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
